language: python
install:
    - pip install --upgrade pip
    - pip install tox coveralls
matrix:
    include:
    - python: "3.4"
      env:
        - TOX_ENV=py3
    - python: "3.4"
      env:
        - TOX_ENV=pylint
    - python: "3.4"
      env:
        - TOX_ENV=doc
    - python: "3.4"
      env:
        - TOX_ENV=examples-py3
    - python: "2.7"
      env:
        - TOX_ENV=py27
    - python: "2.7"
      env:
        - TOX_ENV=examples-py27
script: tox -e $TOX_ENV
after_success: coveralls
